pipeline{
    agent any
    tools{
        go 'go-1.17'
    }

    environment{
        GO111MODULE = 'on'
    }

    stages{
        stage('Development'){
            steps{
                git 'https://github.com/dahalapaar/go-webapp-sample.git'
            }
        }

        stage('Building our image'){
            steps{
                script{
                    app = docker.build('adminturneddevops/go-webapp-sample')
                }
            }
        }
    }
}