pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                // Get some code from a GitHub repository
                git 'https://github.com/dahalapaar/go-webapp-sample.git'
            }
        }
    }
}