pipeline{
    agent any
    tools{
        go 'go-1.17'
    }

    environment{
        GO11MODULE = 'on'
    }

    stages{
        stage('Test'){
            steps{
                git 'https://github.com/dahalapaar/go-webapp-sample.git'
                sh 'go test ./...'
            }
        }

        stage('Build'){
            steps{
                git 'https://github.com/dahalapaar/go-webapp-sample.git'
                sh 'go build .'
            }
        }

        stage('Run'){
            steps{
                sh 'cd /var/lib/jenkins/workspace/go-full-cicd-pipeline && go-webapp-sample &'
            }
        }
    }
}