apiVersion: v1
kind: Service
metadata:
  name: r-service
  labels:
    name: r-service
    app: demo-v-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: r-app-pod
    app: demo-r-app
