apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-app-deploy
  labels:
    name: r-app-deploy
    app: demo-v-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: r-app-pod
      app: demo-r-app
  template:
    metadata:
      name: r-app-pod
      labels:
        name: r-app-pod
        app: demo-r-app
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
