apiVersion: v1
kind: Service
metadata:
  name: v-service
  labels:
    name: v-service
    app: demo-v-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: v-app-pod
    app: demo-v-app
