pipeline{
    agent any

    stages{
        stage('Dev'){
            steps{
                // Get some code from GitHub
                git 'https://github.com/dahalapaar/DevOps.git'
            }
        }

        stage('UAT'){
            steps{
                // Get some code from GitHub
                git 'https://github.com/dahalapaar/DevOps.git'
            }
        }
    }
}